# Generated by Django 5.1.6 on 2025-03-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_model', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
