# Generated by Django 5.1.6 on 2025-03-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_model', '0004_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True),
        ),
    ]
