services:
  web:
    build: .
    user: "1000:1000"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000" # Change both ports if necessary
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true